plugins:
  - rubocop-metz

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - rubocop-metz/test/fixtures/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - rubocop-metz/lib/rubocop-metz.rb

Metrics/MethodLength:
  Exclude:
    - rubocop-metz/test/**/*

Metz/MethodsTooLong:
  Exclude:
    - rubocop-metz/test/**/*

Metz/ClassesTooLong:
  Exclude:
    - rubocop-metz/test/**/*

Metz/DemeterTrainWreck:
  Exclude:
    - rubocop-metz/test/**/*

Metrics/ModuleLength:
  Exclude:
    - rubocop-metz/test/**/*

Metrics/ClassLength:
  Exclude:
    - rubocop-metz/test/**/*

Metrics/AbcSize:
  Exclude:
    - rubocop-metz/test/**/*

Style/FormatStringToken:
  Exclude:
    - rubocop-metz/test/**/*

Style/OneClassPerFile:
  Exclude:
    - rubocop-metz/test/**/*
