plugins:
  - rubocop-metz

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - rubocop-metz/lib/rubocop-metz.rb
